### ISSUE TITLE
Consider submitting this package to elpa, or GNU Emacs core

### ISSUE THREAD

**Issue by VitalyAnkh** [KaranAhlawat/scala-ts-mode#1]
There are no similar packages within elpa or GNU Emacs. Please consider submitting this package to these.

This should be a long-term goal, and you should keep the code style and license compliant with GNU Emacs to achieve this :heart:.

**Comment by KaranAhlawat** [comment]
I agree. I'd like for it to be in an official repository too, but the package is far from a stable state. Maybe once that happens, I'll see what the process for submitting it to one of those is.

On the other hand, do you have any references for the code style that is compliant with GNU Emacs?

**Comment by VitalyAnkh** [comment]
I suggest adding some elisp checks: https://github.com/KaranAhlawat/scala-ts-mode/pull/2

I'm also learning tree-sitter. Will contribute to the parser someday.

**Comment by KaranAhlawat** [comment]
Thank you so much!
Feel free to ask if you have any questions regarding tree-sitter (or the package in general).

I'll be keeping this issue open till we get it to a package repository.

**Comment by KaranAhlawat** [comment]
Okay, so to my (pleasent) surprise, this package is now available on MELPA, thanks to @0kaguya .
I will be closing this issue and updating the README.
