### ISSUE TITLE
Strings and variable names are not highlighted in scala-ts-mode compared to scala-mode

### ISSUE THREAD

**Issue by Flowdalic** [KaranAhlawat/scala-ts-mode#12]
First of all, thanks of working on scala-ts-mode. It has made working with brace-less Scala 3 code in Emacs very comfortable.

However, I found that, when using scala-ts-mode, Emacs does not highlight strings and variable names.

Compare scala-mode

![Screenshot from 2024-02-01 13-38-44](https://github.com/KaranAhlawat/scala-ts-mode/assets/432385/5a43b2f6-cfe0-4d3b-ac38-a94a33568d5c)

with scala-ts-mode

![Screenshot from 2024-02-01 13-39-24](https://github.com/KaranAhlawat/scala-ts-mode/assets/432385/e9b07c19-8321-42ab-a773-f112f8654ac8)

Is there maybe a configuration option I am missing?

**Comment by KaranAhlawat** [comment]
From just the screenshots, it looks like the `treesit-font-lock-level` variable is not set sufficiently. This variable by default is 3, which does not include variables, literals (strings included) etc.

So, in your configuration, can you please try setting `treesit-font-lock-level` to 4 
```lisp
(setq treesit-font-lock-level 4)
```
and then re-opening the Scala file?

**Comment by kschwarz1116** [comment]
Chiming in here to say that I was experiencing the same thing and that change worked for me. Thanks for the pointer! Might be nice to add that to the README.

**Comment by SethTisue** [comment]
oh wow, amazing, thank you!!! I had been meaning to come ask about this

**Comment by SethTisue** [comment]
putting the word out: https://fosstodon.org/@SethTisue/111858506965158147

I also put the word out in a few relevant places on Discord

**Comment by KaranAhlawat** [comment]
@Flowdalic Can we mark this issue as resolved then?

**Comment by SethTisue** [comment]
before & after images

<img width="1291" alt="Screenshot 2024-02-02 at 10 44 50 AM" src="https://github.com/KaranAhlawat/scala-ts-mode/assets/161079/84adf08a-5b1f-4256-9154-1dc091bdd998">
<img width="1247" alt="Screenshot 2024-02-02 at 10 45 41 AM" src="https://github.com/KaranAhlawat/scala-ts-mode/assets/161079/9cb9ed14-65c2-453d-9e59-bd39f9b68229">

**Comment by Flowdalic** [comment]
Actually, I am re-opening this, until this is documented in the README. I may submit a PR for that.

**Comment by SethTisue** [comment]
@Flowdalic I've submitted my own PR: #16
