### ISSUE TITLE
scala-ts-mode and emacs 30

### ISSUE THREAD

**Issue by ahbc-sdg** [KaranAhlawat/scala-ts-mode#14]
Hi, I built tree-sitter-scala grammar using the instructions

When I run scala-ts-mode on a scala file I get

```
There is no recipe for scala, do you want to build it interactively? (y or n) y
Cloning repository
Compiling library
Library installed to /home/andrew/.emacs.d/tree-sitter/libtree-sitter-scala.so
treesit-range-rules: Symbol's function definition is void: treesit-query-compile
```

And closing and opening emacs, opening the scala file, I get
```
File mode specification error: (void-function treesit-query-compile)
```

**Comment by KaranAhlawat** [comment]
Please provide some more information regarding your setup, namely your version of Emacs and whether it was built with tree-sitter-support (I suspect it was, but just to be sure, check the value of `system-configuration-options` or `system-configuration-features`.)

**Comment by ahbc-sdg** [comment]
Hi thank you for your reply

GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0) of 2024-03-05

system-configuration-options is a variable defined in 'C source code'.

Its value is "--with-pgtk"

String containing the configuration options Emacs was built with.

system-configuration-features is a variable defined in 'C source code'.

Its value is
"ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM GTK3 ZLIB"

String listing some of the main features this Emacs was compiled with.
An element of the form "FOO" generally means that HAVE_FOO was
defined during the build.

This is mainly intended for diagnostic purposes in bug reports.
Don't rely on it for testing whether a feature you want to use is available.

  Probably introduced at or before Emacs version 25.1.

**Comment by ahbc-sdg** [comment]
I found that I built it with only 
```
  110  cd emacs
  111  ./autogen.sh
  112  ./configure --with-pgtk
  113  make clean -j8
```

Closing this issue as it was my fault for not building it with treesitter

**Comment by ahbc-sdg** [comment]
hi @KaranAhlawat 
after reinstall emacs with the following

./configure --with-imagemagick --with-tree-sitter --with-pgtk --with-json --with-mailutils

it works! thank you for the help

**Comment by KaranAhlawat** [comment]
Cool, good to know
