### ISSUE TITLE
Comment starting position is not correctlty detected

### ISSUE THREAD

**Issue by kurnevsky** [KaranAhlawat/scala-ts-mode#17]
`(nth 8 (syntax-ppss))` returns nil when point is inside a comment which is not correct, see https://www.gnu.org/software/emacs/manual/html_node/elisp/Parser-State.html

For strings it works fine.

**Comment by kurnevsky** [comment]
It doesn't work only for `//` comments, but for `/* */` it's fine.

**Comment by KaranAhlawat** [comment]
May I ask what the use case is for this?

**Comment by kurnevsky** [comment]
I have my own function that I bind to `<end>` key that goes not to the line end but to the end of code, i.e. place where comment starts if any: https://github.com/kurnevsky/nixfiles/blob/461069fcbf63411d716df51847ac77b3b01afbb8/modules/emacs/init.el#L1634-L1657

It works everywhere except for `scala-ts-mode` :)

**Comment by KaranAhlawat** [comment]
Alright, I'm not very well versed with Emacs syntax-tables but I'll try to see what it's about. 

In the meantime, PRs are welcome if you have any clues as to how to solve this issue

**Comment by KaranAhlawat** [comment]
@kurnevsky Could you try your use case now? We've just got a commit fixing this issue. Please re-open if the issue persists.
