### ISSUE TITLE
Document which grammar version to use

### ISSUE THREAD

**Issue by huanie** [KaranAhlawat/scala-ts-mode#21]
Hi I am getting some font-lock errors when using latest commit from https://github.com/tree-sitter/tree-sitter-scala/commit/a9af6356f8e31f04e870587bca79bc2b15808ff5.
Please document in the README which version to use or add a function that installs the correct grammar.

**Comment by KaranAhlawat** [comment]
Could you post the errors here? Would give me a sense of what version of grammar the package currently supports

**Comment by huanie** [comment]
Example error:
```scala
object Test:
  print("Hello word")
```
``Error during redisplay: (jit-lock-function 19) signaled (treesit-query-error "Node type error at" 135 "(boolean_literal) @font-lock-constant-face (integer_literal) @font-lock-number-face (floating_point_literal) @font-lock-number-face [(symbol_literal) (string) (character_literal)] @font-lock-string-face" "Debug the query with `treesit-query-validate'")``

You get this when typing/indenting.

**Comment by KaranAhlawat** [comment]
Okay so, while I try and fix this (and get the package up to speed with newer versions), you can use version 0.23.2, that seems to work for me.

**Comment by KaranAhlawat** [comment]
Hey, I was able to fix that one, apparently `symbol_literal` was removed and I failed to notice that it was. I'll push the fix, can you try that, still with 0.23.2?

**Comment by huanie** [comment]
Yes it works
