### ISSUE TITLE
Plain comment is highlighted as doc

### ISSUE THREAD

**Issue by kurnevsky** [KaranAhlawat/scala-ts-mode#6]
scala-mode:
![Screenshot_20230923_101201](https://github.com/KaranAhlawat/scala-ts-mode/assets/2943605/758cc2e4-f0b4-4953-94ee-37d1df33d23f)

scala-ts-mode:
![Screenshot_20230923_101224](https://github.com/KaranAhlawat/scala-ts-mode/assets/2943605/920c0968-345f-4743-83d3-c1a362710fd6)

**Comment by KaranAhlawat** [comment]
Thanks for reporting, I'll look into it shortly.

**Comment by KaranAhlawat** [comment]
![image](https://github.com/KaranAhlawat/scala-ts-mode/assets/56113511/c70e0cbb-94c5-472c-818f-9bd885d78f0b)
Closed by #7.

Please test this out and re-open the issue if there are any issues.

1. Pull the latest Scala grammar.
2. Pull the latest commit of `scala-ts-mode` package.
3. Test out the bug fix.

**Comment by kurnevsky** [comment]
Thanks! It's not that easy for me to update grammars  if they don't have a release tag unfortunately...

**Comment by kurnevsky** [comment]
Is it expected that the highlighting is broken with the latest release of the grammar after this change? It doesn't highlight a lot of things anymore, like `package_clause`, `class_definition`, etc.

**Comment by KaranAhlawat** [comment]
Uh no, that's not expected at all. I wouldn't be surprised if the grammar was changed and I just didn't notice though. Could you open a separate issue for this? Along with a reproducible example I can employ.

**Comment by kurnevsky** [comment]
No, that's not a change of the grammar - I use latest release. The only change I had is this repo :)
