### ISSUE TITLE
Broken highlighting with the latest updates

### ISSUE THREAD

**Issue by kurnevsky** [KaranAhlawat/scala-ts-mode#8]
Commit `e933ecd72d58e4dc02b81c8e2ed23da2f1948358`:
![Screenshot_20230925_140138](https://github.com/KaranAhlawat/scala-ts-mode/assets/2943605/e5c2662b-fe48-42e9-b493-7ea8764af3d3)

Commit `771ae55a2bbb1c9a58ade68ee704d2b8d7097a73`:
![Screenshot_20230925_135832](https://github.com/KaranAhlawat/scala-ts-mode/assets/2943605/7ea151ff-7ec2-4751-8be7-c5c5c5c80870)

Note that I use the latest release of scala grammar which is `0.20.2`, not the latest `master`.

**Comment by KaranAhlawat** [comment]
Hi, thanks for reporting the issue.
I tested this myself using the latest commit of this repository, and `0.20.2` tag of the Scala grammar. However, I'm unable to reproduce, as can be seen below.

![image](https://github.com/KaranAhlawat/scala-ts-mode/assets/56113511/cc3ac6d2-d134-4897-9280-1cab84da2fad)

If you have any other ideas for how I could reproduce this, please let me know.

**Comment by kurnevsky** [comment]
I missed that I also have these errors in messages buffer:
```
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 36 "(comment) @font-lock-comment-face (block_comment) @font-lock-comment-face" "Debug the query with `treesit-query-validate'")
Error during redisplay: (jit-lock-function 45) signaled (treesit-query-error "Node type error at" 36 "(comment) @font-lock-comment-face (block_comment) @font-lock-comment-face" "Debug the query with `treesit-query-validate'")
Error during redisplay: (jit-lock-function 1545) signaled (treesit-query-error "Node type error at" 36 "(comment) @font-lock-comment-face (block_comment) @font-lock-comment-face" "Debug the query with `treesit-query-validate'")
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 36 "(comment) @font-lock-comment-face (block_comment) @font-lock-comment-face" "Debug the query with `treesit-query-validate'")
```

And actually I'm using an outdated `0.20.0` grammar :)

**Comment by KaranAhlawat** [comment]
Okay, so I took a look at it, and the problem is, block_comment was only added in 0.20.1, and that's most likely why you're getting the error (because block_comment is not a valid node).
Could you possibly update the grammar to at least 0.20.1 and see if that fixes the issue?

**Comment by kurnevsky** [comment]
Yeah, I'm trying to: https://github.com/NixOS/nixpkgs/pull/257416 :)

**Comment by KaranAhlawat** [comment]
Ah, classic Nix 🤣

**Comment by kurnevsky** [comment]
My PR was merged - it works fine now.
