### ISSUE TITLE
Wrong parser state after comment

### ISSUE THREAD

**Issue by kurnevsky** [KaranAhlawat/scala-ts-mode#9]
Insert a comment `/**/` in scala file and execute `(syntax-ppss)` at any place after this comment. It will show in the 4th argument (see https://www.gnu.org/software/emacs/manual/html_node/elisp/Parser-State.html) that it's inside a comment which is wrong. This breaks some parser-dependent functionality, like `highlight-indent-guides`.

**Comment by KaranAhlawat** [comment]
@kurnevsky This should be fixed by the latest commit. Could you please test it out and let me know?

**Comment by kurnevsky** [comment]
Yep, it's fixed, thanks.
